/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const SubjectId = IDL.Nat;
export const Assignment = IDL.Record({
  'isSubmitted' : IDL.Bool,
  'title' : IDL.Text,
  'dueDate' : Timestamp,
  'submittedAt' : IDL.Opt(Timestamp),
  'description' : IDL.Text,
  'subjectId' : SubjectId,
});
export const AssignmentId = IDL.Nat;
export const EventType = IDL.Variant({
  'assignment' : IDL.Null,
  'exam' : IDL.Null,
  'event' : IDL.Null,
});
export const Event = IDL.Record({
  'title' : IDL.Text,
  'date' : Timestamp,
  'description' : IDL.Text,
  'subjectId' : IDL.Opt(SubjectId),
  'eventType' : EventType,
});
export const EventId = IDL.Nat;
export const NotificationType = IDL.Variant({
  'warning' : IDL.Null,
  'info' : IDL.Null,
  'success' : IDL.Null,
});
export const Notification = IDL.Record({
  'title' : IDL.Text,
  'userId' : IDL.Principal,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'relatedItemId' : IDL.Opt(IDL.Nat),
});
export const NotificationId = IDL.Nat;
export const Course = IDL.Text;
export const Subject = IDL.Record({
  'totalMarks' : IDL.Nat,
  'professorName' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'marksObtained' : IDL.Nat,
  'practicalDate' : Timestamp,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'attendancePercent' : IDL.Nat,
  'examDate' : Timestamp,
  'course' : Course,
});
export const Record = IDL.Record({
  'day' : IDL.Nat,
  'month' : IDL.Nat,
  'isPresent' : IDL.Bool,
  'date' : Timestamp,
  'year' : IDL.Nat,
  'subjectId' : SubjectId,
});
export const StudentId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const StudentProfile = IDL.Record({
  'id' : StudentId,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'course' : IDL.Text,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Message = IDL.Record({
  'isGroupMessage' : IDL.Bool,
  'isRead' : IDL.Bool,
  'toUserId' : IDL.Principal,
  'fromUserId' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
});
export const AttendanceId = IDL.Nat;

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAssignment' : IDL.Func([Assignment], [AssignmentId], []),
  'createEvent' : IDL.Func([Event], [EventId], []),
  'createNotification' : IDL.Func([Notification], [NotificationId], []),
  'createSubject' : IDL.Func([Subject], [SubjectId], []),
  'getAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
  'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getAssignmentsForSubject' : IDL.Func(
      [SubjectId],
      [IDL.Vec(Assignment)],
      ['query'],
    ),
  'getAttendanceHistory' : IDL.Func([SubjectId], [IDL.Vec(Record)], ['query']),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getEvents' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Event)], ['query']),
  'getEventsForMonth' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Event)],
      ['query'],
    ),
  'getMessagesWithUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getProfile' : IDL.Func([StudentId], [IDL.Opt(StudentProfile)], ['query']),
  'getSubject' : IDL.Func([SubjectId], [IDL.Opt(Subject)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([NotificationId], [], []),
  'markSubjectComplete' : IDL.Func([SubjectId], [], []),
  'recordAttendance' : IDL.Func([Record], [AttendanceId], []),
  'registerOrUpdateProfile' : IDL.Func([StudentProfile], [StudentId], []),
  'saveCallerUserProfile' : IDL.Func([StudentProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'submitAssignment' : IDL.Func([AssignmentId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const SubjectId = IDL.Nat;
  const Assignment = IDL.Record({
    'isSubmitted' : IDL.Bool,
    'title' : IDL.Text,
    'dueDate' : Timestamp,
    'submittedAt' : IDL.Opt(Timestamp),
    'description' : IDL.Text,
    'subjectId' : SubjectId,
  });
  const AssignmentId = IDL.Nat;
  const EventType = IDL.Variant({
    'assignment' : IDL.Null,
    'exam' : IDL.Null,
    'event' : IDL.Null,
  });
  const Event = IDL.Record({
    'title' : IDL.Text,
    'date' : Timestamp,
    'description' : IDL.Text,
    'subjectId' : IDL.Opt(SubjectId),
    'eventType' : EventType,
  });
  const EventId = IDL.Nat;
  const NotificationType = IDL.Variant({
    'warning' : IDL.Null,
    'info' : IDL.Null,
    'success' : IDL.Null,
  });
  const Notification = IDL.Record({
    'title' : IDL.Text,
    'userId' : IDL.Principal,
    'notificationType' : NotificationType,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'relatedItemId' : IDL.Opt(IDL.Nat),
  });
  const NotificationId = IDL.Nat;
  const Course = IDL.Text;
  const Subject = IDL.Record({
    'totalMarks' : IDL.Nat,
    'professorName' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'marksObtained' : IDL.Nat,
    'practicalDate' : Timestamp,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'attendancePercent' : IDL.Nat,
    'examDate' : Timestamp,
    'course' : Course,
  });
  const Record = IDL.Record({
    'day' : IDL.Nat,
    'month' : IDL.Nat,
    'isPresent' : IDL.Bool,
    'date' : Timestamp,
    'year' : IDL.Nat,
    'subjectId' : SubjectId,
  });
  const StudentId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const StudentProfile = IDL.Record({
    'id' : StudentId,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'course' : IDL.Text,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Message = IDL.Record({
    'isGroupMessage' : IDL.Bool,
    'isRead' : IDL.Bool,
    'toUserId' : IDL.Principal,
    'fromUserId' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const AttendanceId = IDL.Nat;
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAssignment' : IDL.Func([Assignment], [AssignmentId], []),
    'createEvent' : IDL.Func([Event], [EventId], []),
    'createNotification' : IDL.Func([Notification], [NotificationId], []),
    'createSubject' : IDL.Func([Subject], [SubjectId], []),
    'getAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
    'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getAssignmentsForSubject' : IDL.Func(
        [SubjectId],
        [IDL.Vec(Assignment)],
        ['query'],
      ),
    'getAttendanceHistory' : IDL.Func(
        [SubjectId],
        [IDL.Vec(Record)],
        ['query'],
      ),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversations' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getEvents' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Event)], ['query']),
    'getEventsForMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Event)],
        ['query'],
      ),
    'getMessagesWithUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getProfile' : IDL.Func([StudentId], [IDL.Opt(StudentProfile)], ['query']),
    'getSubject' : IDL.Func([SubjectId], [IDL.Opt(Subject)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([NotificationId], [], []),
    'markSubjectComplete' : IDL.Func([SubjectId], [], []),
    'recordAttendance' : IDL.Func([Record], [AttendanceId], []),
    'registerOrUpdateProfile' : IDL.Func([StudentProfile], [StudentId], []),
    'saveCallerUserProfile' : IDL.Func([StudentProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'submitAssignment' : IDL.Func([AssignmentId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };