/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assignment {
  'isSubmitted' : boolean,
  'title' : string,
  'dueDate' : Timestamp,
  'submittedAt' : [] | [Timestamp],
  'description' : string,
  'subjectId' : SubjectId,
}
export type AssignmentId = bigint;
export type AttendanceId = bigint;
export type Course = string;
export interface Event {
  'title' : string,
  'date' : Timestamp,
  'description' : string,
  'subjectId' : [] | [SubjectId],
  'eventType' : EventType,
}
export type EventId = bigint;
export type EventType = { 'assignment' : null } |
  { 'exam' : null } |
  { 'event' : null };
export type ExternalBlob = Uint8Array;
export interface Message {
  'isGroupMessage' : boolean,
  'isRead' : boolean,
  'toUserId' : Principal,
  'fromUserId' : Principal,
  'message' : string,
  'timestamp' : Timestamp,
}
export interface Notification {
  'title' : string,
  'userId' : Principal,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'message' : string,
  'relatedItemId' : [] | [bigint],
}
export type NotificationId = bigint;
export type NotificationType = { 'warning' : null } |
  { 'info' : null } |
  { 'success' : null };
export interface Record {
  'day' : bigint,
  'month' : bigint,
  'isPresent' : boolean,
  'date' : Timestamp,
  'year' : bigint,
  'subjectId' : SubjectId,
}
export type StudentId = bigint;
export interface StudentProfile {
  'id' : StudentId,
  'name' : string,
  'year' : bigint,
  'email' : string,
  'address' : string,
  'phone' : string,
  'course' : string,
  'avatar' : [] | [ExternalBlob],
}
export interface Subject {
  'totalMarks' : bigint,
  'professorName' : string,
  'isCompleted' : boolean,
  'marksObtained' : bigint,
  'practicalDate' : Timestamp,
  'name' : string,
  'year' : bigint,
  'attendancePercent' : bigint,
  'examDate' : Timestamp,
  'course' : Course,
}
export type SubjectId = bigint;
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAssignment' : ActorMethod<[Assignment], AssignmentId>,
  'createEvent' : ActorMethod<[Event], EventId>,
  'createNotification' : ActorMethod<[Notification], NotificationId>,
  'createSubject' : ActorMethod<[Subject], SubjectId>,
  'getAllAssignments' : ActorMethod<[], Array<Assignment>>,
  'getAllSubjects' : ActorMethod<[], Array<Subject>>,
  'getAssignmentsForSubject' : ActorMethod<[SubjectId], Array<Assignment>>,
  'getAttendanceHistory' : ActorMethod<[SubjectId], Array<Record>>,
  'getCallerProfile' : ActorMethod<[], [] | [StudentProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversations' : ActorMethod<[], Array<Principal>>,
  'getEvents' : ActorMethod<[bigint, bigint], Array<Event>>,
  'getEventsForMonth' : ActorMethod<[bigint, bigint], Array<Event>>,
  'getMessagesWithUser' : ActorMethod<[Principal], Array<Message>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getProfile' : ActorMethod<[StudentId], [] | [StudentProfile]>,
  'getSubject' : ActorMethod<[SubjectId], [] | [Subject]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [StudentProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[NotificationId], undefined>,
  'markSubjectComplete' : ActorMethod<[SubjectId], undefined>,
  'recordAttendance' : ActorMethod<[Record], AttendanceId>,
  'registerOrUpdateProfile' : ActorMethod<[StudentProfile], StudentId>,
  'saveCallerUserProfile' : ActorMethod<[StudentProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'submitAssignment' : ActorMethod<[AssignmentId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];