/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type EventId = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Event {
    title: string;
    date: Timestamp;
    description: string;
    subjectId?: SubjectId;
    eventType: EventType;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type AttendanceId = bigint;
export type StudentId = bigint;
export type Course = string;
export interface StudentProfile {
    id: StudentId;
    name: string;
    year: bigint;
    email: string;
    address: string;
    phone: string;
    course: string;
    avatar?: ExternalBlob;
}
export interface Record_ {
    day: bigint;
    month: bigint;
    isPresent: boolean;
    date: Timestamp;
    year: bigint;
    subjectId: SubjectId;
}
export type NotificationId = bigint;
export interface Notification {
    title: string;
    userId: Principal;
    notificationType: NotificationType;
    createdAt: Timestamp;
    isRead: boolean;
    message: string;
    relatedItemId?: bigint;
}
export interface Message {
    isGroupMessage: boolean;
    isRead: boolean;
    toUserId: Principal;
    fromUserId: Principal;
    message: string;
    timestamp: Timestamp;
}
export type AssignmentId = bigint;
export interface Assignment {
    isSubmitted: boolean;
    title: string;
    dueDate: Timestamp;
    submittedAt?: Timestamp;
    description: string;
    subjectId: SubjectId;
}
export interface Subject {
    totalMarks: bigint;
    professorName: string;
    isCompleted: boolean;
    marksObtained: bigint;
    practicalDate: Timestamp;
    name: string;
    year: bigint;
    attendancePercent: bigint;
    examDate: Timestamp;
    course: Course;
}
export type SubjectId = bigint;
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum EventType {
    assignment = "assignment",
    exam = "exam",
    event = "event"
}
export enum NotificationType {
    warning = "warning",
    info = "info",
    success = "success"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAssignment(assignment: Assignment): Promise<AssignmentId>;
    createEvent(event: Event): Promise<EventId>;
    createNotification(notification: Notification): Promise<NotificationId>;
    createSubject(subject: Subject): Promise<SubjectId>;
    getAllAssignments(): Promise<Array<Assignment>>;
    getAllSubjects(): Promise<Array<Subject>>;
    getAssignmentsForSubject(subjectId: SubjectId): Promise<Array<Assignment>>;
    getAttendanceHistory(subjectId: SubjectId): Promise<Array<Record_>>;
    getCallerProfile(): Promise<StudentProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConversations(): Promise<Array<Principal>>;
    getEvents(month: bigint, year: bigint): Promise<Array<Event>>;
    getEventsForMonth(month: bigint, year: bigint): Promise<Array<Event>>;
    getMessagesWithUser(otherUserId: Principal): Promise<Array<Message>>;
    getNotifications(): Promise<Array<Notification>>;
    getProfile(studentId: StudentId): Promise<StudentProfile | null>;
    getSubject(id: SubjectId): Promise<Subject | null>;
    getUserProfile(user: Principal): Promise<StudentProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markAllNotificationsRead(): Promise<void>;
    markNotificationRead(id: NotificationId): Promise<void>;
    markSubjectComplete(subjectId: SubjectId): Promise<void>;
    recordAttendance(record: Record_): Promise<AttendanceId>;
    registerOrUpdateProfile(newProfile: StudentProfile): Promise<StudentId>;
    saveCallerUserProfile(profile: StudentProfile): Promise<void>;
    sendMessage(toUserId: Principal, message: string): Promise<void>;
    submitAssignment(id: AssignmentId): Promise<void>;
}
import type { Assignment as _Assignment, Event as _Event, EventType as _EventType, ExternalBlob as _ExternalBlob, Notification as _Notification, NotificationType as _NotificationType, StudentId as _StudentId, StudentProfile as _StudentProfile, Subject as _Subject, SubjectId as _SubjectId, Timestamp as _Timestamp, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAssignment(arg0: Assignment): Promise<AssignmentId> {
        if (this.processError) {
            try {
                const result = await this.actor.createAssignment(to_candid_Assignment_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAssignment(to_candid_Assignment_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createEvent(arg0: Event): Promise<EventId> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(to_candid_Event_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(to_candid_Event_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createNotification(arg0: Notification): Promise<NotificationId> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(to_candid_Notification_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(to_candid_Notification_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createSubject(arg0: Subject): Promise<SubjectId> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubject(arg0);
            return result;
        }
    }
    async getAllAssignments(): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssignments();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssignments();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSubjects(): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubjects();
            return result;
        }
    }
    async getAssignmentsForSubject(arg0: SubjectId): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignmentsForSubject(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignmentsForSubject(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceHistory(arg0: SubjectId): Promise<Array<Record_>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceHistory(arg0);
            return result;
        }
    }
    async getCallerProfile(): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversations(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversations();
            return result;
        }
    }
    async getEvents(arg0: bigint, arg1: bigint): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvents(arg0, arg1);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvents(arg0, arg1);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventsForMonth(arg0: bigint, arg1: bigint): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsForMonth(arg0, arg1);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsForMonth(arg0, arg1);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessagesWithUser(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesWithUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesWithUser(arg0);
            return result;
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: StudentId): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubject(arg0: SubjectId): Promise<Subject | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubject(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubject(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAllNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markNotificationRead(arg0: NotificationId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async markSubjectComplete(arg0: SubjectId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markSubjectComplete(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markSubjectComplete(arg0);
            return result;
        }
    }
    async recordAttendance(arg0: Record_): Promise<AttendanceId> {
        if (this.processError) {
            try {
                const result = await this.actor.recordAttendance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordAttendance(arg0);
            return result;
        }
    }
    async registerOrUpdateProfile(arg0: StudentProfile): Promise<StudentId> {
        if (this.processError) {
            try {
                const result = await this.actor.registerOrUpdateProfile(await to_candid_StudentProfile_n43(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerOrUpdateProfile(await to_candid_StudentProfile_n43(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: StudentProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_StudentProfile_n43(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_StudentProfile_n43(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async submitAssignment(arg0: AssignmentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAssignment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAssignment(arg0);
            return result;
        }
    }
}
function from_candid_Assignment_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Assignment): Assignment {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_EventType_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventType): EventType {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Event_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_NotificationType_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
async function from_candid_StudentProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentProfile): Promise<StudentProfile> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentProfile]): Promise<StudentProfile | null> {
    return value.length === 0 ? null : await from_candid_StudentProfile_n25(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubjectId]): SubjectId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Subject]): Subject | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isSubmitted: boolean;
    title: string;
    dueDate: _Timestamp;
    submittedAt: [] | [_Timestamp];
    description: string;
    subjectId: _SubjectId;
}): {
    isSubmitted: boolean;
    title: string;
    dueDate: Timestamp;
    submittedAt?: Timestamp;
    description: string;
    subjectId: SubjectId;
} {
    return {
        isSubmitted: value.isSubmitted,
        title: value.title,
        dueDate: value.dueDate,
        submittedAt: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.submittedAt)),
        description: value.description,
        subjectId: value.subjectId
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StudentId;
    name: string;
    year: bigint;
    email: string;
    address: string;
    phone: string;
    course: string;
    avatar: [] | [_ExternalBlob];
}): Promise<{
    id: StudentId;
    name: string;
    year: bigint;
    email: string;
    address: string;
    phone: string;
    course: string;
    avatar?: ExternalBlob;
}> {
    return {
        id: value.id,
        name: value.name,
        year: value.year,
        email: value.email,
        address: value.address,
        phone: value.phone,
        course: value.course,
        avatar: record_opt_to_undefined(await from_candid_opt_n27(_uploadFile, _downloadFile, value.avatar))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    date: _Timestamp;
    description: string;
    subjectId: [] | [_SubjectId];
    eventType: _EventType;
}): {
    title: string;
    date: Timestamp;
    description: string;
    subjectId?: SubjectId;
    eventType: EventType;
} {
    return {
        title: value.title,
        date: value.date,
        description: value.description,
        subjectId: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.subjectId)),
        eventType: from_candid_EventType_n35(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    userId: Principal;
    notificationType: _NotificationType;
    createdAt: _Timestamp;
    isRead: boolean;
    message: string;
    relatedItemId: [] | [bigint];
}): {
    title: string;
    userId: Principal;
    notificationType: NotificationType;
    createdAt: Timestamp;
    isRead: boolean;
    message: string;
    relatedItemId?: bigint;
} {
    return {
        title: value.title,
        userId: value.userId,
        notificationType: from_candid_NotificationType_n40(_uploadFile, _downloadFile, value.notificationType),
        createdAt: value.createdAt,
        isRead: value.isRead,
        message: value.message,
        relatedItemId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.relatedItemId))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assignment: null;
} | {
    exam: null;
} | {
    event: null;
}): EventType {
    return "assignment" in value ? EventType.assignment : "exam" in value ? EventType.exam : "event" in value ? EventType.event : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    warning: null;
} | {
    info: null;
} | {
    success: null;
}): NotificationType {
    return "warning" in value ? NotificationType.warning : "info" in value ? NotificationType.info : "success" in value ? NotificationType.success : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Assignment>): Array<Assignment> {
    return value.map((x)=>from_candid_Assignment_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n38(_uploadFile, _downloadFile, x));
}
function to_candid_Assignment_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Assignment): _Assignment {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_EventType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): _EventType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Event_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Event): _Event {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_NotificationType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): _NotificationType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_Notification_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Notification): _Notification {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_StudentProfile_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentProfile): Promise<_StudentProfile> {
    return await to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isSubmitted: boolean;
    title: string;
    dueDate: Timestamp;
    submittedAt?: Timestamp;
    description: string;
    subjectId: SubjectId;
}): {
    isSubmitted: boolean;
    title: string;
    dueDate: _Timestamp;
    submittedAt: [] | [_Timestamp];
    description: string;
    subjectId: _SubjectId;
} {
    return {
        isSubmitted: value.isSubmitted,
        title: value.title,
        dueDate: value.dueDate,
        submittedAt: value.submittedAt ? candid_some(value.submittedAt) : candid_none(),
        description: value.description,
        subjectId: value.subjectId
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    date: Timestamp;
    description: string;
    subjectId?: SubjectId;
    eventType: EventType;
}): {
    title: string;
    date: _Timestamp;
    description: string;
    subjectId: [] | [_SubjectId];
    eventType: _EventType;
} {
    return {
        title: value.title,
        date: value.date,
        description: value.description,
        subjectId: value.subjectId ? candid_some(value.subjectId) : candid_none(),
        eventType: to_candid_EventType_n14(_uploadFile, _downloadFile, value.eventType)
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    userId: Principal;
    notificationType: NotificationType;
    createdAt: Timestamp;
    isRead: boolean;
    message: string;
    relatedItemId?: bigint;
}): {
    title: string;
    userId: Principal;
    notificationType: _NotificationType;
    createdAt: _Timestamp;
    isRead: boolean;
    message: string;
    relatedItemId: [] | [bigint];
} {
    return {
        title: value.title,
        userId: value.userId,
        notificationType: to_candid_NotificationType_n18(_uploadFile, _downloadFile, value.notificationType),
        createdAt: value.createdAt,
        isRead: value.isRead,
        message: value.message,
        relatedItemId: value.relatedItemId ? candid_some(value.relatedItemId) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: StudentId;
    name: string;
    year: bigint;
    email: string;
    address: string;
    phone: string;
    course: string;
    avatar?: ExternalBlob;
}): Promise<{
    id: _StudentId;
    name: string;
    year: bigint;
    email: string;
    address: string;
    phone: string;
    course: string;
    avatar: [] | [_ExternalBlob];
}> {
    return {
        id: value.id,
        name: value.name,
        year: value.year,
        email: value.email,
        address: value.address,
        phone: value.phone,
        course: value.course,
        avatar: value.avatar ? candid_some(await to_candid_ExternalBlob_n45(_uploadFile, _downloadFile, value.avatar)) : candid_none()
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): {
    assignment: null;
} | {
    exam: null;
} | {
    event: null;
} {
    return value == EventType.assignment ? {
        assignment: null
    } : value == EventType.exam ? {
        exam: null
    } : value == EventType.event ? {
        event: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): {
    warning: null;
} | {
    info: null;
} | {
    success: null;
} {
    return value == NotificationType.warning ? {
        warning: null
    } : value == NotificationType.info ? {
        info: null
    } : value == NotificationType.success ? {
        success: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
